### ISSUE TITLE
[DS][COL] After update to 0.2.1

### ISSUE THREAD

**Issue by drakray** [the-realest-stu/Thaumic-Periphery#1]
https://pastebin.com/tfU9zws9
```
java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:254)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:304)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:263)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:263)
    at thaumicperiphery.ModContent.registerEntities(ModContent.java:63)
```
Client load fine, Dedicated Server Crash On Load with this
MC 1.12.2
Forege 2690
TP 0.2.1

**Comment by the-realest-stu** [comment]
Just submitted a new version to curseforge which should resolve this issue. It should be available soon.

**Comment by drakray** [comment]
Thanks, work nicely :D
